CREATE TABLE IF NOT EXISTS metric_daily (
  day TEXT NOT NULL,
  event TEXT NOT NULL,
  n INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (day, event)
);

ALTER TABLE users ADD COLUMN role TEXT NOT NULL DEFAULT 'user';
